# -*- coding: utf-8 -*-
"""compare_face_images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uOIk_fOEDD89V-5XjK14Hlcvw9-vNXuq
"""

!pip install deepface

from deepface import DeepFace
import cv2
import matplotlib.pyplot as plt

img1 = cv2.imread('/content/AakashID.png')
plt.imshow(img1[:,:,::-1])
plt.show()

img2 = cv2.imread('/content/AjayID.png')
plt.imshow(img2[:,:,::-1])
plt.show()

result = DeepFace.verify(img1,img2)

print("Is same face: ", result["verified"])